[features]
seeds = false
skip-lint = false

[programs.localnet]
token_amm = "$PROGRAM_ID"

[programs.devnet]
token_amm = "$PROGRAM_ID"

[programs.mainnet]
token_amm = "$PROGRAM_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "$ANCHOR_PROVIDER_URL"
wallet = "$ANCHOR_WALLET"

[workspace]
members = ["programs/token-2022-amm"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

