[features]
seeds = false
skip-lint = false

[programs.localnet]
token_amm = "AcVqvDTmYKLpHM1o1WnkUAHPT6vxRomaSfFji9wRY1m7"

[programs.devnet]
token_amm = "AcVqvDTmYKLpHM1o1WnkUAHPT6vxRomaSfFji9wRY1m7"

[programs.mainnet]
token_amm = "AcVqvDTmYKLpHM1o1WnkUAHPT6vxRomaSfFji9wRY1m7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[build]
# Remove this line to let Anchor handle the build process
# cargo-build-command = "cargo build-bpf"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"