[features]
seeds = false
skip-lint = false

[programs.localnet]
token_amm = "2516vhAXsYH9co7EPrW1k2oMnHUq7yS6eHerftbVaqms"

[programs.devnet]
token_amm = "2516vhAXsYH9co7EPrW1k2oMnHUq7yS6eHerftbVaqms"

[programs.mainnet]
token_amm = "2516vhAXsYH9co7EPrW1k2oMnHUq7yS6eHerftbVaqms"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/token-2022-amm"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"